# Generated by Django 4.1.4 on 2022-12-27 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragon',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dragon',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dragon',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dragon',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
