# Generated by Django 4.1.4 on 2022-12-27 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gui', '0002_dragon_for_sale_dragon_owner_dragon_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragon',
            name='shared_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dragon',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
