# Generated by Django 4.1.4 on 2023-02-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_fight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
