# Generated by Django 4.1.3 on 2022-11-10 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
        name='Dragon',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(max_length=90)),
            ('hp', models.IntegerField(default=1)),
            ('attack', models.IntegerField(default=1)),
            ('defense', models.IntegerField(default=1)),
            ('speed', models.IntegerField(default=1)),
        ], 
    ),
    ]
